/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dryeye_app_CView_SCALE */

#ifndef _Included_com_dryeye_app_CView_SCALE
#define _Included_com_dryeye_app_CView_SCALE
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
