/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_allergoscope_app_wifi_FragmentSync_SendThread */

#ifndef _Included_com_allergoscope_app_wifi_FragmentSync_SendThread
#define _Included_com_allergoscope_app_wifi_FragmentSync_SendThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_allergoscope_app_wifi_FragmentSync_SendThread_MIN_PRIORITY
#define com_allergoscope_app_wifi_FragmentSync_SendThread_MIN_PRIORITY 1L
#undef com_allergoscope_app_wifi_FragmentSync_SendThread_NORM_PRIORITY
#define com_allergoscope_app_wifi_FragmentSync_SendThread_NORM_PRIORITY 5L
#undef com_allergoscope_app_wifi_FragmentSync_SendThread_MAX_PRIORITY
#define com_allergoscope_app_wifi_FragmentSync_SendThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
