/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_allergoscope_app_wifi_SyncThread */

#ifndef _Included_com_allergoscope_app_wifi_SyncThread
#define _Included_com_allergoscope_app_wifi_SyncThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_allergoscope_app_wifi_SyncThread_RUN_TRUE
#define com_allergoscope_app_wifi_SyncThread_RUN_TRUE 1L
#undef com_allergoscope_app_wifi_SyncThread_RUN_FALSE
#define com_allergoscope_app_wifi_SyncThread_RUN_FALSE 2L
/*
 * Class:     com_allergoscope_app_wifi_SyncThread
 * Method:    DetachCppThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_allergoscope_app_wifi_SyncThread_DetachCppThread
  (JNIEnv *, jobject);

/*
 * Class:     com_allergoscope_app_wifi_SyncThread
 * Method:    TryConnect
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_allergoscope_app_wifi_SyncThread_TryConnect
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_allergoscope_app_wifi_SyncThread
 * Method:    LoopThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_allergoscope_app_wifi_SyncThread_LoopThread
  (JNIEnv *, jobject);

/*
 * Class:     com_allergoscope_app_wifi_SyncThread
 * Method:    SendFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_allergoscope_app_wifi_SyncThread_SendFile
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     com_allergoscope_app_wifi_SyncThread
 * Method:    Write
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_allergoscope_app_wifi_SyncThread_Write
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_allergoscope_app_wifi_SyncThread
 * Method:    GetROI
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_allergoscope_app_wifi_SyncThread_GetROI
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_allergoscope_app_wifi_SyncThread
 * Method:    GetFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_allergoscope_app_wifi_SyncThread_GetFile
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_allergoscope_app_wifi_SyncThread
 * Method:    ReadMdnsRecords
 * Signature: ([BI)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_allergoscope_app_wifi_SyncThread_ReadMdnsRecords
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_allergoscope_app_wifi_SyncThread
 * Method:    CreateMdnsRecords
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_allergoscope_app_wifi_SyncThread_CreateMdnsRecords
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_allergoscope_app_wifi_SyncThread
 * Method:    CreateMdnsRecords2W
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_allergoscope_app_wifi_SyncThread_CreateMdnsRecords2W
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
