/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_allergoscope_app_MenuActivity_COnClickButton */

#ifndef _Included_com_allergoscope_app_MenuActivity_COnClickButton
#define _Included_com_allergoscope_app_MenuActivity_COnClickButton
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
