/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_allergoscope_app_wifi_FragmentSync */

#ifndef _Included_com_allergoscope_app_wifi_FragmentSync
#define _Included_com_allergoscope_app_wifi_FragmentSync
#ifdef __cplusplus
extern "C" {
#endif
#undef com_allergoscope_app_wifi_FragmentSync_INITIALIZING
#define com_allergoscope_app_wifi_FragmentSync_INITIALIZING 0L
#undef com_allergoscope_app_wifi_FragmentSync_CREATED
#define com_allergoscope_app_wifi_FragmentSync_CREATED 1L
#undef com_allergoscope_app_wifi_FragmentSync_ACTIVITY_CREATED
#define com_allergoscope_app_wifi_FragmentSync_ACTIVITY_CREATED 2L
#undef com_allergoscope_app_wifi_FragmentSync_STARTED
#define com_allergoscope_app_wifi_FragmentSync_STARTED 3L
#undef com_allergoscope_app_wifi_FragmentSync_RESUMED
#define com_allergoscope_app_wifi_FragmentSync_RESUMED 4L
#ifdef __cplusplus
}
#endif
#endif
