/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_allergoscope_app_wifi_SyncThread_Profile */

#ifndef _Included_com_allergoscope_app_wifi_SyncThread_Profile
#define _Included_com_allergoscope_app_wifi_SyncThread_Profile
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
