/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_common_CThread */

#ifndef _Included_lib_common_CThread
#define _Included_lib_common_CThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_common_CThread
 * Method:    _Start
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_lib_common_CThread__1Start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_common_CThread
 * Method:    _Submit
 * Signature: (JILjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_lib_common_CThread__1Submit
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     lib_common_CThread
 * Method:    _Stop
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_lib_common_CThread__1Stop
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
