/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_common_CObject */

#ifndef _Included_lib_common_CObject
#define _Included_lib_common_CObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_common_CObject
 * Method:    CreateGlobalInstance
 * Signature: (Ljava/lang/Class;)Llib/utils/GlobalRef;
 */
JNIEXPORT jobject JNICALL Java_lib_common_CObject_CreateGlobalInstance
        (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
