/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_utils_AGlobals */

#ifndef _Included_lib_utils_AGlobals
#define _Included_lib_utils_AGlobals
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_utils_AGlobals
 * Method:    SendCommand2Thread
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_lib_utils_AGlobals_SendCommand2Thread
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     lib_utils_AGlobals
 * Method:    PostCommand2Thread
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_lib_utils_AGlobals_PostCommand2Thread
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     lib_utils_AGlobals
 * Method:    CallCommand
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_lib_utils_AGlobals_CallCommand
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     lib_utils_AGlobals
 * Method:    AttachThread
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_lib_utils_AGlobals_AttachThread
  (JNIEnv *, jclass, jlong);

/*
 * Class:     lib_utils_AGlobals
 * Method:    DetachThread
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_lib_utils_AGlobals_DetachThread
  (JNIEnv *, jclass, jlong);

/*
 * Class:     lib_utils_AGlobals
 * Method:    OnThreadLoop
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_lib_utils_AGlobals_OnThreadLoop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     lib_utils_AGlobals
 * Method:    LongToObject
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_lib_utils_AGlobals_LongToObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     lib_utils_AGlobals
 * Method:    ReleaseGlobalInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lib_utils_AGlobals_ReleaseGlobalInstance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     lib_utils_AGlobals
 * Method:    AddGlobalIdle
 * Signature: (Llib/common/ActionCallback;)V
 */
JNIEXPORT void JNICALL Java_lib_utils_AGlobals_AddGlobalIdle
  (JNIEnv *, jclass, jobject);

/*
 * Class:     lib_utils_AGlobals
 * Method:    ReleaseGlobalIdle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_utils_AGlobals_ReleaseGlobalIdle
  (JNIEnv *, jclass);

/*
 * Class:     lib_utils_AGlobals
 * Method:    ReadString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lib_utils_AGlobals_ReadString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     lib_utils_AGlobals
 * Method:    SaveIni
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_lib_utils_AGlobals_SaveIni
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     lib_utils_AGlobals
 * Method:    ReadIni
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lib_utils_AGlobals_ReadIni
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     lib_utils_AGlobals
 * Method:    SaveIniW
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_lib_utils_AGlobals_SaveIniW
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     lib_utils_AGlobals
 * Method:    ReadIniW
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lib_utils_AGlobals_ReadIniW
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     lib_utils_AGlobals
 * Method:    ReadLang
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lib_utils_AGlobals_ReadLang
  (JNIEnv *, jclass);

/*
 * Class:     lib_utils_AGlobals
 * Method:    WriteLang
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_lib_utils_AGlobals_WriteLang
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
