/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_utils_AGlobals_CasheFromExplore */

#ifndef _Included_lib_utils_AGlobals_CasheFromExplore
#define _Included_lib_utils_AGlobals_CasheFromExplore
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
